### ISSUE TITLE
graphql-live-query-patch: better list diffing

### ISSUE THREAD

**Issue by n1ru4l** [n1ru4l/graphql-live-query#308]
The patches generated for lists are currently pretty BAD. If there was a possibility for giving JSON patch a hint via the id of an object that could help with generating more efficient patches (as it then can identify a single object as removed from a list instead of all items as changed).

Related: https://github.com/Starcounter-Jack/JSON-Patch/issues/91 https://github.com/Starcounter-Jack/JSON-Patch/issues/92

**Comment by n1ru4l** [comment]
Oh this looks promising: https://github.com/benjamine/jsondiffpatch

**Comment by n1ru4l** [comment]
There has been a bit of silence here. Now I wanna pick it up again and I wonder what would be the best solution to offer both json-patch and jsondiffpatch support. I guess we could somehow make the [`graphql-live-query-patch`](https://github.com/n1ru4l/graphql-live-query/tree/main/packages/graphql-live-query-patch) more modular aka provide your own patcher function (with recipes) or have `@n1ru4l/graphql-live-query-json-patch` and `@n1ru4l/graphql-live-query-json-diff-patch` package 🤔

**Comment by marcus-sa** [comment]
Modularity is always preferred in my opinion.
Having multiple packages published just for providing a patcher option seems redundant.
I'd rather install one of `jsondiffpatch` or `json-patch` separately as an optional dependency and simply provide it to `@n1ru4l/graphql-live-query`

**Comment by n1ru4l** [comment]
Some thoughts on how I wanna continue shaping graphql-live-query: https://dev.to/n1ru4l/graphql-live-queries-backed-by-the-relay-specification-3mlo

**Comment by Venryx** [comment]
> There has been a bit of silence here. Now I wanna pick it up again and I wonder what would be the best solution to offer both json-patch and jsondiffpatch support. I guess we could somehow make the [`graphql-live-query-patch`](https://github.com/n1ru4l/graphql-live-query/tree/main/packages/graphql-live-query-patch) more modular aka provide your own patcher function (with recipes) or have `@n1ru4l/graphql-live-query-json-patch` and `@n1ru4l/graphql-live-query-json-diff-patch` package 🤔

I agree with @marcus-sa that a modular approach is much preferred.

That said, looking through the source code of `graphql-live-query-patch`, it appears that one can already swap in a custom `generatePatch` and `applyPatch` functions?

Field by which to supply a custom `generatePatch` function: https://github.com/n1ru4l/graphql-live-query/blob/c3d13b598376dfd3d26ffac1c89d19517a1c28b6/packages/graphql-live-query-patch/src/createLiveQueryPatchGenerator.ts#L18
Field by which to supply a custom `applyPatch` function: https://github.com/n1ru4l/graphql-live-query/blob/c3d13b598376dfd3d26ffac1c89d19517a1c28b6/packages/graphql-live-query-patch/src/createApplyLiveQueryPatch.ts#L23

Are your comments above about making the swap-in process even easier, eg. by passing in a simple module name instead of a specific function?

**Comment by n1ru4l** [comment]
Hey @Venryx, I think the best solution would be to change graphql-live-query-patch to contain the common logic shared between both json patch and jsondiff and then have two packages that have the shared dependeny of the common logic. One for json patch and one for jsondiff.

I would really appreciate your help on this task 😌

**Comment by Venryx** [comment]
I got too impatient, so I implemented the "easy patch-lib swapping" a layer above, in my [postgraphile-live-query](https://github.com/pg-lq/postgraphile-live-query) packages. (readme [section here](https://github.com/pg-lq/postgraphile-live-query#generatepatchesplugin) shows how to switch between them)

At some point, I agree it would be good to have this sort of easier patch-lib swapping in the `graph-live-query` layer, but I'm too lazy to do that atm unfortunately. ^_^

That said, I am happy to report that the patch-library you found above (https://github.com/benjamine/jsondiffpatch) works as advertised, correctly detecting when an array item was "merely moved/reordered/deleted", and thus sending a single patch entry -- instead of a series of "field replacements" for all later array entries, as happens for `fast-json-patch`.

Screenshot of websocket message after deleting a middle-of-list array item:
![](https://i.imgur.com/xwt4axc.png)

As can be seen, the patch entry for the item deletion avoids the "cascade" of changes (for later array items) that is normally generated.

That said, the [delta format that jsondiffpatch uses](https://github.com/benjamine/jsondiffpatch/blob/master/docs/deltas.md) is arguably less "human readable" than the standardized [json-patch](http://jsonpatch.com) one that [fast-json-patch](https://github.com/martindale/fast-json-patch) uses.

That's a tradeoff I'll accept for greater efficiency for large lists, however. I've thus set `jsondiffpatch` as the default patch-library for my layer-2 [postgraphile-live-query](https://github.com/pg-lq/postgraphile-live-query) packages.

**Comment by n1ru4l** [comment]
I created https://github.com/n1ru4l/graphql-live-query/pull/581 which splits `@n1ru4l/graphql-live-query-patch` into  `@n1ru4l/graphql-live-query-patch` and  `@n1ru4l/graphql-live-query-patch-json-patch`. The former contains shared logic for all patch packages, the latter the specific logic for json-patch. I also added `@n1ru4l/graphql-live-query-patch-jsondiffpatch` based upon `jsondiffpatch`. While doing so I noticed that the patches generated by `jsondiffpatch` always include the previous value (as it is more a general diff). Thus it is not optimal :/ There is a feature request for making the original value optional (https://github.com/benjamine/jsondiffpatch/issues/244), however, nobody has tackled this yet.

**Comment by Venryx** [comment]
> While doing so I noticed that the patches generated by jsondiffpatch always include the previous value (as it is more a general diff). Thus it is not optimal :/

Agreed, it has some unnecessary data sent along; I'd rather have that than the cascade of changes from array-item moves/deletions, but it's still not ideal. I suppose it's possible to add some code that just scans through the patch object, replacing the field holding the old-value with `0` or something (like the commenter in the thread you linked described), though this would add some processing overhead; it's probably worth it for the bandwidth savings though.

As for the packages, I tend to think it's a bad idea to be creating whole new packages simply for different patching mechanisms. While there are only two options we're looking at now (fast-json-patch and jsondiffpatch), I found like half a dozen others while searching, and there are likely plenty more. The two we have now are not even "ideal" imo, since neither is being maintained all that actively atm. Will you really want to maintain all the variant packages even if you someday move on to something better?

Also, the list of packages in `graphql-live-query` was already enough that it was a bit confusing when I first found the repo. The creation of new packages for different patching libraries may make this problem worse, perhaps slowing adoption.

Is there a reason you don't want to use a more modular approach, say where you just have a wiki page with "recipes" showing minimal wrapper functions to integrate each patching library with your "graphql-live-query-patch" library? The wrapper functions are only like four lines each, so this should be feasible, while avoiding package-count expansion.
***
Looking through the pull request, I suppose one advantage of creating new packages for each patching library is that you can add separate unit-tests for each one. While that is an advantage, is that necessary if there are already unit tests for "graphql-live-query-patch", and in the main repos for each patching library? The patching functions are "self-contained", so as long as the "framework" and the "plug-in" are passing their own tests, there doesn't seem to be much room/need for additional tests specific to the integration.

All that to say, thank you for your time working on this topic, as it's something that is important to solve for websites with larger result sets. Once you've fully decided on how you want to structure the patch-library swap-in system, I'll take another look and rework how my layer-2 swap-in system uses (or extends) the customizable in "graphql-live-query-patch".

**Comment by n1ru4l** [comment]
I don't see a draw pack for providing packages that ship with the glue code, they are great for getting started. Anyone who wants to customize the functionality per default can simply use the graphql-live-query-patch package. For me the maintenance overhead is not that big and having examples that are covered by CI is better than some recipe that gets outdated (,however, there are probably ways of doing that smarter).

**Comment by n1ru4l** [comment]
https://github.com/n1ru4l/graphql-live-query/pull/692 improves list diffing a lot and thus I will close this issue
